### ISSUE TITLE
error when bitbake elkpi-audio-os-image

### ISSUE THREAD

**Issue by cuanyu** [elk-audio/elkpi-yocto-layers#2]
I am trying to build the image for rpi4 and I got this error while bitbake elkpi-audio-os-image:

tom@ubuntuYJY:~/elkpi/build$ bitbake elkpi-audio-os-image
Traceback (most recent call last):
  File "/home/tom/elkpi/layers/bitbake/bin/bitbake", line 19, in <module>
    import bb
  File "/home/tom/elkpi/layers/bitbake/lib/bb/__init__.py", line 128, in <module>
    from bb import fetch2 as fetch
  File "/home/tom/elkpi/layers/bitbake/lib/bb/fetch2/__init__.py", line 26, in <module>
    import bb.persist_data, bb.utils
  File "/home/tom/elkpi/layers/bitbake/lib/bb/persist_data.py", line 22, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

I have other Yocto projects build on this same machine and they seem to be working fine. What should I check for this?

**Comment by shdrmr** [comment]
Hey, this seems to be due to the fact that you are using a distro that is
not supported for yocto builds especially for the hardknott version. I
faced this issue when I upgraded my build machine to Ubuntu 22.10.

It is trying to use python3.10 which causes a lot of issues in hardknott.

My suggestion is do one of these two:
1. Wait for a few days as we are going to release the latest version for
Elk Audio OS (kitkstone).
2. Install a docker image with Ubuntu 18 or 20 and then build the layers.
You should be able to do so without any problems.

Sharan

**Comment by cuanyu** [comment]
Hi Sharan. Yes I am running 22.04 and yocto does warn me that it is not tested for this version of Ubuntu. I am curious about why the difference in Ubuntu version would impact Yocto so much. For simple projects it seems to be fine. But for complex ones all sorts of errors surface. I will wait for a few days for the new Kirkstone release. After that if the problem is still there I go with the docker way. Thanks

**Comment by shdrmr** [comment]
That's usually because of upgrades to the host systems packages such as
python3,glibc etc. Yocto uses these to parse and build the "native"
packages and then using those out builds the target packages. When the
distro packages are incompatible, a lot of things break with either parsing
the recipes or building the native packages

Sharan
